### ISSUE TITLE
Introduce the notion of packages

### ISSUE THREAD

**Issue by gfngfn** [gfngfn/Sesterl#7]
In Sesterl, a *package* is represented by a single module, called the *main module* which typically has some submodules. It is declared by a configuration file in YAML:

```yaml
package: "http"
language_version: "0.1.0"
package_version: "0.1.0"

authors:
  - "Taro Tanaka"
  - "John Smith"

dependencies:
  - package: "tcp"
    source:
      type: "git"
      repository: "bitbucket.org/foo/tcp"
      constraints:
        - type: minimum
          value: "1.2.0"

  - package: "parser"
    source:
      type: "git"
      repository: "github.com/bar/parser"
      constraints:
        - type: minimum
          value: "2.0.0"

source_directories:
  - "./src"

main_module: "./src/container.sest"
```

Here, `source_directories` stands for the directories where source files are put. `main_module` specifies the source file which defines the main module.

```
src/
├── container.sest
├── server.sest
├── client.sest
├── request.sest
├── response.sest
└── util.sest
```

Only the main module can be referenced from the outside. A relatively small package consists of a single module, which corresponds to the main module of the package. A larger package, on the other hand, consists of multiple source files each of which defines a module, and one of the source files defines the main module. In the latter case, modules other than the main module are usually either only for internal use, or imported by the main module as submodules.

```
/* src/container.sest: the main module */
use Server
use Client
use Request
use Response

module Http :> sig
  module Request : sig … end
  module Response : sig … end
  module Server : sig … end
  module Client : sig … end
end = struct
  module Server = Server
  module Client = Client
  module Request = Request
  module Response = Response
end
```

Modules are detected from the source directories specified in the configuration file, and topologically sorted based on the dependency among them. A source file defines a module like the following:

```
/* src/server.sest */
require Tcp
use Util
use Request
use Response

module Server :> sig
  type t
  val start : …
  …
end = struct
  …
end
```

Here, `require` declares the dependency on an external package, whereas `use` declares the dependency on another module within the package. Note that modules other than the main module can have module members like the following:

```
module Foo :> sig
  module Sub : sig … end
  signature S = sig … end
  module F : (X : S) -> sig … end
end = struct
  module Sub = struct … end
  signature S = sig … end
  module F = fun(X : S) -> struct … end
end
```

Based on the dependency, a whole module tree for the package like the following will be internally constructed:

```
require Tcp
require Parser

module Http :> sig
  module Request : sig … end
  module Response : sig … end
  module Server : sig … end
  module Client : sig … end
end = struct
  module Util = struct … end
  module Request = struct … end
  module Response = struct … end
  module Server = struct … end
  module Client = struct … end
end
