### ISSUE TITLE
Support dependency on external packages

### ISSUE THREAD

**Issue by gfngfn** [gfngfn/Sesterl#8]
```yaml
dependencies:
  - package: "another_package"
    source:
      type: "local"
      path: "./path/to/another_package/"
 - package: "fetched_package"
    source:
      type: "git"
      repository: "github.com/some_user/fetched_package"
      constraints:
        - type: "minimum"
          value: "0.1.0"
```
